AWSTemplateFormatVersion: 2010-09-09

Parameters:

  EnvironmentName:
    Description: Select the environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod

  MyKeyName:
    Description: Select the environment
    Type: AWS::EC2::KeyPair::KeyName

Mappings:
  MyRegionMap:
    us-east-2:
      AMIID: ami-02f97949d306b597a
    us-west-2:
      AMIID: ami-0efa651876de2a5ce

  MyEnvironmentMap:
    dev:
      InstanceType: t2.micro
    qa:
      InstanceType: t2.small
    prod:
      InstanceType: t2.small

Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - AMIID
      InstanceType: !FindInMap
        - MyEnvironmentMap
        - !Ref EnvironmentName
        - InstanceType
      KeyName: !Ref MyKeyName
      SecurityGroups: 
        - !Ref DevEnvSecurityGroup

  DevEnvSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My Dev environment Global Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

Outputs:
  MyInstanceId:
    Description: My Instance Id
    Value: !Ref MyVMInstance