AWSTemplateFormatVersion: 2010-09-09

Parameters:
  MyKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the Keypair

  EnvironmentName:
    Description: Select the environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Mappings:
  MyRegionMap:
    us-east-2:
      AMIID: ami-02f97949d306b597a
    us-west-2:
      AMIID: ami-0efa651876de2a5ce

  MyEnvironmentMap:
    dev:
      InstanceType: t2.micro
    prod:
      InstanceType: t2.small

Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - AMIID
      InstanceType: !FindInMap
        - MyEnvironmentMap
        - !Ref EnvironmentName
        - InstanceType
      KeyName: !Ref MyKeyName
