AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyVMInstance:
    Type: AWS::eC2::Instance
    Properties:
      ImageId: ami-02f97949d306b597a
      InstanceType: t2.micro
      KeyName: cfn-key-1
