AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 Instance.

Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02f97949d306b597a
      InstanceType: t2.micro
      KeyName: cfn-key-1
      SecurityGroups:
        - default