AWSTemplateFormatVersion: 2010-09-09
Description: Keyname parameter demo

Parameters:
  MyKeyName:
    Description: Select the key name from the list
    Type: AWS::EC2::KeyPair::KeyName

  MyAvailbilityZone:
    Description: Select the AZ from the list
    Type: String
    Default: us-east-2a
    AllowedValues:
      - us-east-2a
      - us-east-2b
      - us-east-2c

  MyInstanceType:
    Description: Select the Instance Type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small

Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02f97949d306b597a
      InstanceType:
        Description: Select ec2 instacnce from SSM
        Type: AWS::SSM::Parameter::Value<String>
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroups
      AvailabilityZone: !Ref MyAvailbilityZone

  SSHSecurityGroups:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My new SSH security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

