AWSTemplateFormatVersion: 2010-09-09

Parameters:

  EnvironmentName:
    Description: Select the environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod

Mappings:
  MyRegionMap:
    us-east-2:
      AMIID: ami-02f97949d306b597a
    us-west-2:
      AMIID: ami-0efa651876de2a5ce

  MyEnvironmentMap:
    dev:
      InstanceType: t2.micro
    qa:
      InstanceType: t2.small
    prod:
      InstanceType: t2.small

Conditions:
  CreateEIPForProd: !Equals [!Ref EnvironmentName,prod]
  CreateSecurityGroup: !Equals [!Ref EnvironmentName, dev]
  CreateProdSecurityGroup: !Equals [!Ref EnvironmentName, prod]
  CreateDevSecurityGroup: !Not [{condition: CreateProdSecurityGroup}]
  IfRegionUseKeyName: !Or [!Equals [!Ref 'AWS::Region', us-east-2] , [!Ref 'AWS::Region', us-west-2]]

Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - AMIID
      InstanceType: !FindInMap
        - MyEnvironmentMap
        - !Ref EnvironmentName
        - InstanceType
      KeyName: !If [IfRegionUseKeyName, cfn-key-1, cfn-key-2]
      SecurityGroups: !If [CreateSecurityGroup, [!Ref DevEnvSecurityGroup], [!Ref ProdEnvSecurityGroup]]

  MyProdEIP:
    Type: AWS::EC2::EIP
    Condition: CreateEIPForProd
    Properties: 
      InstanceId: !Ref MyVMInstance

  DevEnvSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: CreateSecurityGroup
    Properties:
      GroupDescription: Dev SG
      SecurityGroupIngress:
        - IpProtocol : tcp
          Fromport: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

  ProdEnvSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: CreateProdSecurityGroup
    Properties:
      GroupDescription: Prod SG
      SecurityGroupIngress:
        - IpProtocol : tcp
          Fromport: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0        
