AWSTemplateFormatVersion: '2010-09-09'
Description: SG Stack Template

Parameters:
  VPCId:
    Description: Create a sg in group
    Type: AWS::EC2::VPC::Id

Resources:
  DevSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Dev Apps Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '9080'
          ToPort: '9080'
          CidrIp: 0.0.0.0/0
        
      VpcId: !Ref VPCId

Outputs:
  DevSGId:
    Description: Dev Security Group
    Value: !Ref DevSG